name: untitled
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.17.4
  excel: ^2.0.7
  path_provider: ^2.1.5
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.14.0
  webview_flutter_wkwebview: ^3.13.0
  permission_handler: ^11.4.0
  open_file: ^3.5.4
  universal_html: ^2.2.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
